### ISSUE TITLE
스토리모드 클릭 문제

### ISSUE THREAD

**Issue by shso127** [SEdreamers/Do_yoUNO#58]
스토리모드에서 게임 시작 창을 눌렀을 때, 뒤에 메인 창의 버튼들이 클릭이 되는 오류가 있는데 어떻게 해결하면 좋을까요?

**Comment by chaeyoungeee** [comment]
get_rect 함수 이용해서 클릭 반응 위치 화면 밖으로 이동시키면 될 것 같아요.

**Comment by chaeyoungeee** [comment]
해결했습니다.

**Comment by shso127** [comment]
오 감사합니다:)
